# Conclusion

## Why bother

We’re at the end of this course, which I hope you enjoyed. There is now yet another question we need to ask ourselves: is this worth it?
Why should we bother with making our pipelines reproducible? I believe that there are two, fundamental, essential reasons. 

The first one, is that time is finite, and working manually does not scale. Reproducible pipelines do take time to set up, but they allow
us to win this time back once we start re-running them. Wasting time and resources running things manually (with the potential for introducing
errors) is simply not acceptable. This freed up time can then be used to provide further value to your employer, yourself, and ideally your
community as well.

The second reason, is that setting up RAPs is in itself an enjoyable activity, which requires the full depth and breadth of your skills. 
If you’re working in science, there is the added benefit that by setting up a RAP you’re doing actual science: providing a reproducible
analysis where an hypothesis gets tested (an not writing papers).
